// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift

import UIKit

struct R {
  static func validate() {
    storyboard.launchScreen.validateImages()
    storyboard.launchScreen.validateViewControllers()
    storyboard.main.validateImages()
    storyboard.main.validateViewControllers()
  }
  
  struct file {
    static var bucketsJson: NSURL? { return _R.hostingBundle?.URLForResource("Buckets", withExtension: "json") }
    static var launchScreenStrings: NSURL? { return _R.hostingBundle?.URLForResource("LaunchScreen", withExtension: "strings") }
    static var mainStrings: NSURL? { return _R.hostingBundle?.URLForResource("Main", withExtension: "strings") }
    static var rounded_EleganceTtf: NSURL? { return _R.hostingBundle?.URLForResource("Rounded_Elegance", withExtension: "ttf") }
  }
  
  struct font {
    static func roundedEleganceNewRegular(size size: CGFloat) -> UIFont? {
      return UIFont(name: "RoundedEleganceNew-Regular", size: size)
    }
  }
  
  struct image {
    static var back: UIImage? { return UIImage(named: "back", inBundle: _R.hostingBundle, compatibleWithTraitCollection: nil) }
    static var bookmark: UIImage? { return UIImage(named: "bookmark", inBundle: _R.hostingBundle, compatibleWithTraitCollection: nil) }
    static var bookmarkFill: UIImage? { return UIImage(named: "bookmark-fill", inBundle: _R.hostingBundle, compatibleWithTraitCollection: nil) }
    static var calendar: UIImage? { return UIImage(named: "calendar", inBundle: _R.hostingBundle, compatibleWithTraitCollection: nil) }
    static var calendar_sprite: UIImage? { return UIImage(named: "calendar_sprite", inBundle: _R.hostingBundle, compatibleWithTraitCollection: nil) }
    static var close: UIImage? { return UIImage(named: "close", inBundle: _R.hostingBundle, compatibleWithTraitCollection: nil) }
    static var favorite: UIImage? { return UIImage(named: "favorite", inBundle: _R.hostingBundle, compatibleWithTraitCollection: nil) }
    static var favoriteFill: UIImage? { return UIImage(named: "favorite-fill", inBundle: _R.hostingBundle, compatibleWithTraitCollection: nil) }
    static var filter: UIImage? { return UIImage(named: "filter", inBundle: _R.hostingBundle, compatibleWithTraitCollection: nil) }
    static var grid: UIImage? { return UIImage(named: "grid", inBundle: _R.hostingBundle, compatibleWithTraitCollection: nil) }
    static var list: UIImage? { return UIImage(named: "list", inBundle: _R.hostingBundle, compatibleWithTraitCollection: nil) }
    static var lock: UIImage? { return UIImage(named: "lock", inBundle: _R.hostingBundle, compatibleWithTraitCollection: nil) }
    static var logo: UIImage? { return UIImage(named: "logo", inBundle: _R.hostingBundle, compatibleWithTraitCollection: nil) }
    static var menu: UIImage? { return UIImage(named: "menu", inBundle: _R.hostingBundle, compatibleWithTraitCollection: nil) }
    static var more: UIImage? { return UIImage(named: "more", inBundle: _R.hostingBundle, compatibleWithTraitCollection: nil) }
    static var news: UIImage? { return UIImage(named: "news", inBundle: _R.hostingBundle, compatibleWithTraitCollection: nil) }
    static var phone: UIImage? { return UIImage(named: "phone", inBundle: _R.hostingBundle, compatibleWithTraitCollection: nil) }
    static var portofolio_0: UIImage? { return UIImage(named: "portofolio_0", inBundle: _R.hostingBundle, compatibleWithTraitCollection: nil) }
    static var portofolio_1: UIImage? { return UIImage(named: "portofolio_1", inBundle: _R.hostingBundle, compatibleWithTraitCollection: nil) }
    static var portofolio_2: UIImage? { return UIImage(named: "portofolio_2", inBundle: _R.hostingBundle, compatibleWithTraitCollection: nil) }
    static var portofolio_3: UIImage? { return UIImage(named: "portofolio_3", inBundle: _R.hostingBundle, compatibleWithTraitCollection: nil) }
    static var profile: UIImage? { return UIImage(named: "profile", inBundle: _R.hostingBundle, compatibleWithTraitCollection: nil) }
    static var rank: UIImage? { return UIImage(named: "rank", inBundle: _R.hostingBundle, compatibleWithTraitCollection: nil) }
    static var refresh: UIImage? { return UIImage(named: "refresh", inBundle: _R.hostingBundle, compatibleWithTraitCollection: nil) }
    static var remind: UIImage? { return UIImage(named: "remind", inBundle: _R.hostingBundle, compatibleWithTraitCollection: nil) }
    static var search: UIImage? { return UIImage(named: "search", inBundle: _R.hostingBundle, compatibleWithTraitCollection: nil) }
    static var share: UIImage? { return UIImage(named: "share", inBundle: _R.hostingBundle, compatibleWithTraitCollection: nil) }
    static var user: UIImage? { return UIImage(named: "user", inBundle: _R.hostingBundle, compatibleWithTraitCollection: nil) }
    static var user_0: UIImage? { return UIImage(named: "user_0", inBundle: _R.hostingBundle, compatibleWithTraitCollection: nil) }
    static var user_1: UIImage? { return UIImage(named: "user_1", inBundle: _R.hostingBundle, compatibleWithTraitCollection: nil) }
    static var user_2: UIImage? { return UIImage(named: "user_2", inBundle: _R.hostingBundle, compatibleWithTraitCollection: nil) }
  }
  
  struct nib {
    static var centerView: _R.nib._CenterView { return _R.nib._CenterView() }
    static var homeView: _R.nib._HomeView { return _R.nib._HomeView() }
    static var itemCell: _R.nib._ItemCell { return _R.nib._ItemCell() }
    static var leftView: _R.nib._LeftView { return _R.nib._LeftView() }
    static var menuCell: _R.nib._MenuCell { return _R.nib._MenuCell() }
    static var rightView: _R.nib._RightView { return _R.nib._RightView() }
  }
  
  struct reuseIdentifier {
    
  }
  
  struct segue {
    
  }
  
  struct storyboard {
    struct launchScreen {
      static var initialViewController: UIViewController? { return instance.instantiateInitialViewController() }
      static var instance: UIStoryboard { return UIStoryboard(name: "LaunchScreen", bundle: _R.hostingBundle) }
      
      static func validateImages() {
        
      }
      
      static func validateViewControllers() {
        
      }
    }
    
    struct main {
      static var initialViewController: ViewController? { return instance.instantiateInitialViewController() as? ViewController }
      static var instance: UIStoryboard { return UIStoryboard(name: "Main", bundle: _R.hostingBundle) }
      
      static func validateImages() {
        
      }
      
      static func validateViewControllers() {
        
      }
    }
  }
}

struct _R {
  static var hostingBundle: NSBundle? { return NSBundle(identifier: "official.alfian.MyProject") }
  
  struct nib {
    struct _CenterView: NibResource {
      var instance: UINib { return UINib.init(nibName: "CenterView", bundle: _R.hostingBundle) }
      var name: String { return "CenterView" }
      
      func firstView(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> UIView? {
        return instantiateWithOwner(ownerOrNil, options: optionsOrNil)[0] as? UIView
      }
      
      func instantiateWithOwner(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> [AnyObject] {
        return instance.instantiateWithOwner(ownerOrNil, options: optionsOrNil)
      }
    }
    
    struct _HomeView: NibResource {
      var instance: UINib { return UINib.init(nibName: "HomeView", bundle: _R.hostingBundle) }
      var name: String { return "HomeView" }
      
      func firstView(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> UIView? {
        return instantiateWithOwner(ownerOrNil, options: optionsOrNil)[0] as? UIView
      }
      
      func instantiateWithOwner(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> [AnyObject] {
        return instance.instantiateWithOwner(ownerOrNil, options: optionsOrNil)
      }
    }
    
    struct _ItemCell: NibResource {
      var instance: UINib { return UINib.init(nibName: "ItemCell", bundle: _R.hostingBundle) }
      var name: String { return "ItemCell" }
      
      func firstView(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> ItemCell? {
        return instantiateWithOwner(ownerOrNil, options: optionsOrNil)[0] as? ItemCell
      }
      
      func instantiateWithOwner(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> [AnyObject] {
        return instance.instantiateWithOwner(ownerOrNil, options: optionsOrNil)
      }
    }
    
    struct _LeftView: NibResource {
      var instance: UINib { return UINib.init(nibName: "LeftView", bundle: _R.hostingBundle) }
      var name: String { return "LeftView" }
      
      func firstView(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> UIView? {
        return instantiateWithOwner(ownerOrNil, options: optionsOrNil)[0] as? UIView
      }
      
      func instantiateWithOwner(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> [AnyObject] {
        return instance.instantiateWithOwner(ownerOrNil, options: optionsOrNil)
      }
    }
    
    struct _MenuCell: NibResource {
      var instance: UINib { return UINib.init(nibName: "MenuCell", bundle: _R.hostingBundle) }
      var name: String { return "MenuCell" }
      
      func firstView(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> MenuCell? {
        return instantiateWithOwner(ownerOrNil, options: optionsOrNil)[0] as? MenuCell
      }
      
      func instantiateWithOwner(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> [AnyObject] {
        return instance.instantiateWithOwner(ownerOrNil, options: optionsOrNil)
      }
    }
    
    struct _RightView: NibResource {
      var instance: UINib { return UINib.init(nibName: "RightView", bundle: _R.hostingBundle) }
      var name: String { return "RightView" }
      
      func firstView(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> UIView? {
        return instantiateWithOwner(ownerOrNil, options: optionsOrNil)[0] as? UIView
      }
      
      func instantiateWithOwner(ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]?) -> [AnyObject] {
        return instance.instantiateWithOwner(ownerOrNil, options: optionsOrNil)
      }
    }
  }
}

struct ReuseIdentifier<T>: CustomStringConvertible {
  let identifier: String
  
  var description: String { return identifier }
}

struct StoryboardSegueIdentifier<Segue: UIStoryboardSegue, Source: UIViewController, Destination: UIViewController>: CustomStringConvertible {
  let identifier: String
  
  var description: String { return identifier }
}

struct TypedStoryboardSegueInfo<Segue: UIStoryboardSegue, Source: UIViewController, Destination: UIViewController>: CustomStringConvertible {
  let destinationViewController: Destination
  let identifier: String?
  let segue: Segue
  let sourceViewController: Source
  
  var description: String { return identifier ?? "" }
  
   init?(segue: UIStoryboardSegue) {
    guard let segue = segue as? Segue, sourceViewController = segue.sourceViewController as? Source, destinationViewController = segue.destinationViewController as? Destination else { return nil }
    self.segue = segue
    self.identifier = segue.identifier
    self.sourceViewController = sourceViewController
    self.destinationViewController = destinationViewController
  }
}

protocol NibResource {
  var instance: UINib { get }
  var name: String { get }
}

protocol Reusable {
  typealias T
  
  var reuseIdentifier: ReuseIdentifier<T> { get }
}

extension UITableView {
  func dequeueReusableCellWithIdentifier<T : UITableViewCell>(identifier: ReuseIdentifier<T>, forIndexPath indexPath: NSIndexPath?) -> T? {
    if let indexPath = indexPath {
      return dequeueReusableCellWithIdentifier(identifier.identifier, forIndexPath: indexPath) as? T
    }
    return dequeueReusableCellWithIdentifier(identifier.identifier) as? T
  }
  
  func dequeueReusableCellWithIdentifier<T : UITableViewCell>(identifier: ReuseIdentifier<T>) -> T? {
    return dequeueReusableCellWithIdentifier(identifier.identifier) as? T
  }
  
  func dequeueReusableHeaderFooterViewWithIdentifier<T : UITableViewHeaderFooterView>(identifier: ReuseIdentifier<T>) -> T? {
    return dequeueReusableHeaderFooterViewWithIdentifier(identifier.identifier) as? T
  }
  
  func registerNib<T: NibResource where T: Reusable, T.T: UITableViewCell>(nibResource: T) {
    registerNib(nibResource.instance, forCellReuseIdentifier: nibResource.reuseIdentifier.identifier)
  }
  
  func registerNibForHeaderFooterView<T: NibResource where T: Reusable, T.T: UIView>(nibResource: T) {
    registerNib(nibResource.instance, forHeaderFooterViewReuseIdentifier: nibResource.reuseIdentifier.identifier)
  }
  
  func registerNibs<T: NibResource where T: Reusable, T.T: UITableViewCell>(nibResources: [T]) {
    nibResources.forEach(registerNib)
  }
}

extension UICollectionView {
  func dequeueReusableCellWithReuseIdentifier<T: UICollectionViewCell>(identifier: ReuseIdentifier<T>, forIndexPath indexPath: NSIndexPath) -> T? {
    return dequeueReusableCellWithReuseIdentifier(identifier.identifier, forIndexPath: indexPath) as? T
  }
  
  func dequeueReusableSupplementaryViewOfKind<T: UICollectionReusableView>(elementKind: String, withReuseIdentifier identifier: ReuseIdentifier<T>, forIndexPath indexPath: NSIndexPath) -> T? {
    return dequeueReusableSupplementaryViewOfKind(elementKind, withReuseIdentifier: identifier.identifier, forIndexPath: indexPath) as? T
  }
  
  func registerNib<T: NibResource where T: Reusable, T.T: UICollectionViewCell>(nibResource: T) {
    registerNib(nibResource.instance, forCellWithReuseIdentifier: nibResource.reuseIdentifier.identifier)
  }
  
  func registerNib<T: NibResource where T: Reusable, T.T: UICollectionReusableView>(nibResource: T, forSupplementaryViewOfKind kind: String) {
    registerNib(nibResource.instance, forSupplementaryViewOfKind: kind, withReuseIdentifier: nibResource.reuseIdentifier.identifier)
  }
  
  func registerNibs<T: NibResource where T: Reusable, T.T: UICollectionViewCell>(nibResources: [T]) {
    nibResources.forEach(registerNib)
  }
  
  func registerNibs<T: NibResource where T: Reusable, T.T: UICollectionReusableView>(nibResources: [T], forSupplementaryViewOfKind kind: String) {
    nibResources.forEach { self.registerNib($0, forSupplementaryViewOfKind: kind) }
  }
}

extension UIViewController {
  convenience init(nib: NibResource) {
    self.init(nibName: nib.name, bundle: _R.hostingBundle)
  }
}

extension UIViewController {
  func performSegueWithIdentifier<Segue: UIStoryboardSegue,Source: UIViewController,Destination: UIViewController>(identifier: StoryboardSegueIdentifier<Segue, Source, Destination>, sender: AnyObject?) {
    performSegueWithIdentifier(identifier.identifier, sender: sender)
  }
}

extension UIStoryboardSegue {
  func typedInfoWithIdentifier<Segue: UIStoryboardSegue,Source: UIViewController,Destination: UIViewController>(identifier: StoryboardSegueIdentifier<Segue, Source, Destination>) -> TypedStoryboardSegueInfo<Segue, Source, Destination>? {
    guard self.identifier == identifier.identifier else { return nil }
    return TypedStoryboardSegueInfo(segue: self)
  }
}